#!/bin/bash

# Creating symbolic link for the command dduc
ln -sf "/Applications/Dynamic DNS Update Client.app/Contents/MacOS/dduc" /usr/local/bin/dduc

# Adding service
# Use $RECEIPT_PATH which points to the package contents during installation
RESOURCE_DIR="$RECEIPT_PATH/Contents/Resources"
cp "$RESOURCE_DIR/io.github.henriquemcc.dduc.daemon.plist" /Library/LaunchAgents/
chown root:wheel /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist
chmod 644 /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist

# Loading service
CURRENT_USER=$(stat -f "%Su" /dev/console)
sudo -u "$CURRENT_USER" launchctl load /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist