#!/bin/bash

# Creating symbolic link for the command dduc
ln -sf "/Applications/Dynamic DNS Update Client.app/Contents/MacOS/dduc" /usr/local/bin/dduc

# Adding service
# Use $RECEIPT_PATH which points to the package contents during installation
cat <<EOF > "/Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.github.henriquemcc.dduc.daemon</string>

    <key>ProgramArguments</key>
    <array>
        <string>/Applications/Dynamic DNS Update Client.app/Contents/MacOS/dduc</string>
        <string>daemon</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>/tmp/dduc.out.log</string>

    <key>StandardErrorPath</key>
    <string>/tmp/dduc.err.log</string>
</dict>
</plist>
EOF

# Setting permissions
chown root:wheel /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist
chmod 644 /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist

# Loading service
CURRENT_USER=$(stat -f "%Su" /dev/console)
sudo -u "$CURRENT_USER" launchctl load /Library/LaunchAgents/io.github.henriquemcc.dduc.daemon.plist