import com.netflix.gradle.plugins.deb.Deb
import com.netflix.gradle.plugins.rpm.Rpm
import java.net.URL
import org.redline_rpm.header.Os

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    // Apply the Kotlinx Serialization plugin
    alias(libs.plugins.kotlin.serialization)

    id("com.netflix.nebula.ospackage") version "12.3.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Koin
    implementation(platform(libs.koin.bom))
    implementation(libs.koin.core)

    // Kotlinx Serialization
    implementation(libs.kotlinx.serialization.json)

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "io.github.henriquemcc.dduc.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks {
    withType<Jar> {
        manifest {
            attributes["Main-Class"] = application.mainClass.get()
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }

        configurations["compileClasspath"].forEach { file: File ->
            from(zipTree(file.absoluteFile))
        }
    }
}

// RPM Package Configuration
ospackage {
    packageName = "dynamic-dns-update-client"
    version = project.version.toString()
    release = "1"
    archStr = "NOARCH"
    os = Os.LINUX
}

// DEB Package Configuration
tasks.named<Deb>("buildDeb") {
    archStr = "all"
    distribution = "stable"
    priority = "optional"
    maintainer = "Henrique Mendonça Castelar Campos <henriquemendonacastelar@gmail.com>"
    vendor = maintainer
    license = "EUPL-1.2"
    requires("default-jre-headless | openjdk-17-jre-headless | openjdk-21-jre-headless")
    postInstall(file("../scripts/deb/postinstall.sh"))
    preUninstall(file("../scripts/deb/preuninstall.sh"))

    // Copying the .jar to the .deb package
    from(tasks.jar.get().outputs.files) {
        into("/opt/dduc")
        rename { "app.jar" }
    }

    // Copying the dduc script to the .deb package
    from("../scripts/deb/dduc") {
        into("/usr/bin")
    }
}

tasks.named<Rpm>("buildRpm") {
    archStr = "NOARCH"
    distribution = "el9"
    packager = "Henrique Mendonça Castelar Campos <henriquemendonacastelar@gmail.com>"
    vendor = packager
    license = "EUPL-1.2"
    requires("(java-latest-openjdk-headless or java-21-openjdk-headless or java-25-openjdk-headless or java-17-openjdk-headless)")
    postInstall(file("../scripts/rpm/postinstall.sh"))
    preUninstall(file("../scripts/rpm/preuninstall.sh"))

    // Copying the .jar to the .rpm package
    from(tasks.jar.get().outputs.files) {
        into("/opt/dduc")
        rename { "app.jar" }
    }

    // Copying the dduc script to the .rpm package
    from("../scripts/deb/dduc") {
        into("/usr/bin")
    }
}

val downloadWinSw = tasks.register("downloadWinSw") {
    group = "build setup"
    description = "Downloads the WinSW executables."

    val winSwVersion = "v2.12.0"
    val downloadDir = layout.buildDirectory.dir("winsw-download")
    val downloads = mapOf(
        "WinSW-x64.exe" to "https://github.com/winsw/winsw/releases/download/$winSwVersion/WinSW-x64.exe",
        "WinSW-x86.exe" to "https://github.com/winsw/winsw/releases/download/$winSwVersion/WinSW-x86.exe"
    )

    outputs.dir(downloadDir)

    doLast {
        val targetDir = downloadDir.get().asFile
        targetDir.mkdirs()

        downloads.forEach { (fileName, urlString) ->
            val targetFile = targetDir.resolve(fileName)
            if (!targetFile.exists()) {
                logger.lifecycle("Downloading $fileName from $urlString...")
                URL(urlString).openStream().use { input ->
                    targetFile.outputStream().use { output ->
                        input.copyTo(output)
                    }
                }
            } else {
                logger.lifecycle("$fileName already exists. Skipping download.")
            }
        }
    }
}

tasks.register<Copy>("prepareInstallerFiles") {
    group = "distribution"
    description = "Gathers all files needed for the WiX installer into a staging directory."
    dependsOn(tasks.jar, downloadWinSw)

    // 1. Copy the fat JAR
    from(tasks.jar) {
        rename { "app.jar" }
    }

    // 2. Copy WinSW files from the download task and the local XML config
    // Using the 64-bit version for this installer
    from(downloadWinSw) {

        include("WinSW-x64.exe")
        rename("WinSW-x64.exe", "dduc-service-x64.exe")
    }
    // Using the 32-bit version for this installer
    from(downloadWinSw) {
        include("WinSW-x86.exe")
        rename("WinSW-x86.exe", "dduc-service-x86.exe")
    }

    from("../installer/winsw") {
        // The XML config still lives locally as it's part of your project's source
        include("dduc-service.xml")
    }

    // 3. Put everything into a staging directory that WiX can use
    into(layout.buildDirectory.dir("installer-stage"))
}