/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.henriquemcc.dduc

import io.github.henriquemcc.dduc.cli.Cli
import org.koin.core.context.GlobalContext.startKoin

fun main(args: Array<String>) {
    startKoin {
        modules(koinModule)
    }
    Cli().run(args)
}
